/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lenovo' at '14-10-29 上午9:28' with Gradle 1.10
 *
 * @author lenovo, @date 14-10-29 上午9:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
